name: AWS S3 Activity

on:
  push:
    branches:
      - develop

jobs:
  list-s3-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: List S3 Buckets
      run: |
        aws s3 ls

    - name: List Contents of a Specific S3 Bucket
      run: |
        aws s3 ls s3://demokarthik06/
