name: Authenticate with AWS S

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  authenticate:
    runs-on: self-hosted
    outputs:
      aws-access-key-id: ${{ steps.configure.outputs.aws-access-key-id }}
      aws-secret-access-key: ${{ steps.configure.outputs.aws-secret-access-key }}
      aws-session-token: ${{ steps.configure.outputs.aws-session-token }}
    steps:
      - name: Configure AWS credentials
        id: configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ${{ inputs.aws-region }}
      - name: validate Hostname
        run: hostname
      - name: set the value
        run: |
          echo $aws-access-key-id
      - name: Verify AWS Credentials
        run: |
          echo "Checking AWS Credentials:"
          echo "AWS Access Key ID: ${#AWS_ACCESS_KEY_ID} characters long"
          echo "AWS Secret Access Key: ${#AWS_SECRET_ACCESS_KEY} characters long"
          echo "AWS Session Token: ${#AWS_SESSION_TOKEN} characters long"
          echo "AWS Access Key ID: ${AWS_ACCESS_KEY}"
          echo "AWS Access Key ID: ${#AWS_ACCESS_KEY}"
              
