name: AWS S3 Activity

on:
  workflow_dispatch:

jobs:
  list-s3-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: List directory contents
      run: ls -R .github/workflows/

    - name: Authenticate with AWS
      uses: ./.github/workflows/aws-auth.yml@auth-develop

    - name: List S3 Buckets
      run: |
        aws s3 ls

    - name: List Contents of a Specific S3 Bucket
      run: |
        aws s3 ls s3://demokarthik06/
