name: AWS S3 Activity

on:
  workflow_dispatch:

jobs:
  list-s3-contents:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      id: configure-aws
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Use AWS credentials
      run: |
        aws s3 ls
        # Access outputs from the configure-aws step
        echo "AWS Access Key ID: ${{ needs.configure-aws.outputs.aws-access-key-id }}"
        echo "AWS Secret Access Key: ${{ needs.configure-aws.outputs.aws-secret-access-key }}"
