name: Deploy to AWS

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  authenticate:
    uses: kakugithub/openidconnector/.github/workflows/authenticate.yml@main
    with:
      aws-region: eu-west-3
      role-to-assume: arn:aws:iam::499756076901:role/GitHub_AWS_Role

  deploy:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: |
          aws s3 cp my-app.txt s3://demokarthik06/
