name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  authenticate:
    uses: kakugithub/openidconnector/.github/workflows/authenticate.yml@main
    with:
      aws-region: eu-west-3
      role-to-assume: arn:aws:iam::499756076901:role/GitHub_AWS_Role

  deploy:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy application
        run: aws ssm get-parameter --name=hello_test --query Parameter.Value
