name: AWS Parameter Store

on:
  workflow_dispatch:

jobs:
  aws-parameter-store:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Authenticate with AWS
      uses: ./.github/workflows/aws-auth.yml
      
    - name: Print AWS SSM Parameter
      run: aws ssm get-parameter --name=hello_test --query Parameter.Value

    - name: Print assumed role
      run: aws sts get-caller-identity
